// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: routing.proto

package ttmeshproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Routing/meta cursor as described in Protocol.md
type Metadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RouteRef       *RouteRef              `protobuf:"bytes,1,opt,name=route_ref,json=routeRef,proto3" json:"route_ref,omitempty"`                                                     // link to external route/DAG manifest
	WorkflowId     string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`                                               // workflow instance id
	TaskId         string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                                           // client/task id (idempotency)
	StepId         string                 `protobuf:"bytes,4,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`                                                           // current step in DAG
	NextStep       string                 `protobuf:"bytes,5,opt,name=next_step,json=nextStep,proto3" json:"next_step,omitempty"`                                                     // optional hint for next hop
	HopTtl         uint32                 `protobuf:"varint,6,opt,name=hop_ttl,json=hopTtl,proto3" json:"hop_ttl,omitempty"`                                                          // prevents infinite loops
	Attrs          map[string]string      `protobuf:"bytes,7,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // free-form attributes/labels
	ShardKey       string                 `protobuf:"bytes,8,opt,name=shard_key,json=shardKey,proto3" json:"shard_key,omitempty"`                                                     // computed sharding key (optional)
	DeadlineUnixMs int64                  `protobuf:"varint,9,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`                                // overall workflow deadline (0 if none)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_routing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetRouteRef() *RouteRef {
	if x != nil {
		return x.RouteRef
	}
	return nil
}

func (x *Metadata) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *Metadata) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Metadata) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *Metadata) GetNextStep() string {
	if x != nil {
		return x.NextStep
	}
	return ""
}

func (x *Metadata) GetHopTtl() uint32 {
	if x != nil {
		return x.HopTtl
	}
	return 0
}

func (x *Metadata) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *Metadata) GetShardKey() string {
	if x != nil {
		return x.ShardKey
	}
	return ""
}

func (x *Metadata) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

// Breadcrumbs of routing decisions (trim to last N on sender if needed)
type HopMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                     // who made the decision
	TsUnixMs      int64                  `protobuf:"varint,2,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`            // timestamp
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`                                   // region/geohash or label
	Decision      string                 `protobuf:"bytes,4,opt,name=decision,proto3" json:"decision,omitempty"`                               // concise reason (e.g., "geo+rdv+load")
	ChosenNodeId  string                 `protobuf:"bytes,5,opt,name=chosen_node_id,json=chosenNodeId,proto3" json:"chosen_node_id,omitempty"` // selected target for forwarding
	RttMs         uint32                 `protobuf:"varint,6,opt,name=rtt_ms,json=rttMs,proto3" json:"rtt_ms,omitempty"`                       // optional observed latency
	Sig           []byte                 `protobuf:"bytes,7,opt,name=sig,proto3" json:"sig,omitempty"`                                         // optional hop signature
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HopMeta) Reset() {
	*x = HopMeta{}
	mi := &file_routing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HopMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HopMeta) ProtoMessage() {}

func (x *HopMeta) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HopMeta.ProtoReflect.Descriptor instead.
func (*HopMeta) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{1}
}

func (x *HopMeta) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HopMeta) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

func (x *HopMeta) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *HopMeta) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *HopMeta) GetChosenNodeId() string {
	if x != nil {
		return x.ChosenNodeId
	}
	return ""
}

func (x *HopMeta) GetRttMs() uint32 {
	if x != nil {
		return x.RttMs
	}
	return 0
}

func (x *HopMeta) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

var File_routing_proto protoreflect.FileDescriptor

const file_routing_proto_rawDesc = "" +
	"\n" +
	"\rrouting.proto\x12\fttmesh.proto\x1a\fcommon.proto\"\x82\x03\n" +
	"\bMetadata\x123\n" +
	"\troute_ref\x18\x01 \x01(\v2\x16.ttmesh.proto.RouteRefR\brouteRef\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x17\n" +
	"\astep_id\x18\x04 \x01(\tR\x06stepId\x12\x1b\n" +
	"\tnext_step\x18\x05 \x01(\tR\bnextStep\x12\x17\n" +
	"\ahop_ttl\x18\x06 \x01(\rR\x06hopTtl\x127\n" +
	"\x05attrs\x18\a \x03(\v2!.ttmesh.proto.Metadata.AttrsEntryR\x05attrs\x12\x1b\n" +
	"\tshard_key\x18\b \x01(\tR\bshardKey\x12(\n" +
	"\x10deadline_unix_ms\x18\t \x01(\x03R\x0edeadlineUnixMs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc3\x01\n" +
	"\aHopMeta\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x02 \x01(\x03R\btsUnixMs\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x1a\n" +
	"\bdecision\x18\x04 \x01(\tR\bdecision\x12$\n" +
	"\x0echosen_node_id\x18\x05 \x01(\tR\fchosenNodeId\x12\x15\n" +
	"\x06rtt_ms\x18\x06 \x01(\rR\x05rttMs\x12\x10\n" +
	"\x03sig\x18\a \x01(\fR\x03sigB'Z%ttmesh/pkg/protocol/proto;ttmeshprotob\x06proto3"

var (
	file_routing_proto_rawDescOnce sync.Once
	file_routing_proto_rawDescData []byte
)

func file_routing_proto_rawDescGZIP() []byte {
	file_routing_proto_rawDescOnce.Do(func() {
		file_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routing_proto_rawDesc), len(file_routing_proto_rawDesc)))
	})
	return file_routing_proto_rawDescData
}

var file_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_routing_proto_goTypes = []any{
	(*Metadata)(nil), // 0: ttmesh.proto.Metadata
	(*HopMeta)(nil),  // 1: ttmesh.proto.HopMeta
	nil,              // 2: ttmesh.proto.Metadata.AttrsEntry
	(*RouteRef)(nil), // 3: ttmesh.proto.RouteRef
}
var file_routing_proto_depIdxs = []int32{
	3, // 0: ttmesh.proto.Metadata.route_ref:type_name -> ttmesh.proto.RouteRef
	2, // 1: ttmesh.proto.Metadata.attrs:type_name -> ttmesh.proto.Metadata.AttrsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_routing_proto_init() }
func file_routing_proto_init() {
	if File_routing_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routing_proto_rawDesc), len(file_routing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_routing_proto_goTypes,
		DependencyIndexes: file_routing_proto_depIdxs,
		MessageInfos:      file_routing_proto_msgTypes,
	}.Build()
	File_routing_proto = out.File
	file_routing_proto_goTypes = nil
	file_routing_proto_depIdxs = nil
}
