app_name: ttmesh-node-c
data_dir: ./data-c
# node_id: node-c

identity:
  alg: ed25519
  # private_key: ""
  # private_key_file: ""

log:
  level: info
  format: console
  outputs:
    - stdout
  development: true

transports:
  - kind: udp
    listen: [":9999"]
    dial:
      - address: "127.0.0.1:7777" # to node-a (UDP)
  - kind: tcp
    listen: [":9998"]
    dial:
      - address: "127.0.0.1:7778" # to node-a (TCP)

